-- SQLite
SELECT TRANSACTIONS.SALES
        FROM ((TRANSACTIONS 
        INNER JOIN COUNTRIES ON TRANSACTIONS.COUNTRY = COUNTRIES.ID)
        INNER JOIN PETROLEUM ON TRANSACTIONS.PETROLEUM = PETROLEUM.ID)
        WHERE TRANSACTIONS.COUNTRY = 1 AND TRANSACTIONS.SALES > 0 AND TRANSACTIONS.PETROLEUM = 1;


SELECT SUM(TRANSACTIONS.SALES)
                            FROM ((TRANSACTIONS
                            INNER JOIN PETROLEUM ON PETROLEUM.ID = TRANSACTIONS.PETROLEUM)
                            INNER JOIN YEARS ON YEARS.ID = TRANSACTIONS.YEAR)
                            WHERE TRANSACTIONS.SALES > 0 AND YEARS.YEAR = 2012 AND PETROLEUM.TYPE =  "Furnace Oil"


SELECT * FROM TRANSACTIONS WHERE TRANSACTIONS.YEAR = 1 OR TRANSACTIONS.YEAR = 2

SELECT AVG(TRANSACTIONS.SALES) 
FROM ((TRANSACTIONS
INNER JOIN PETROLEUM ON PETROLEUM.ID = TRANSACTIONS.PETROLEUM)
INNER JOIN YEARS ON YEARS.ID = TRANSACTIONS.YEAR)
WHERE TRANSACTIONS.SALES > 0 AND (YEARS.YEAR = 2007 OR YEARS.YEAR = 2008) AND PETROLEUM.TYPE = "Petrol"